// Generated by aifn — do not edit manually.

package aifunc;

/**
 * Controls the function's runtime mode and model connection.
 * Use {@link AIFuncConfig#builder()} to construct an instance.
 */
public final class AIFuncConfig {

    private final String  baseUrl;
    private final String  apiKey;
    private final String  model;
    private final Double  temperature;
    private final Double  topP;
    private final Integer maxTokens;
    private final int timeoutMs;
    private final int maxRetries;
    private final boolean mock;
    private final Object mockData;

    private AIFuncConfig(Builder b) {
        this.baseUrl     = b.baseUrl;
        this.apiKey      = b.apiKey;
        this.model       = b.model;
        this.temperature = b.temperature;
        this.topP        = b.topP;
        this.maxTokens   = b.maxTokens;
        this.timeoutMs   = b.timeoutMs;
        this.maxRetries  = b.maxRetries;
        this.mock        = b.mock;
        this.mockData    = b.mockData;
    }

    public String  getBaseUrl()     { return baseUrl;     }
    public String  getApiKey()      { return apiKey;      }
    public String  getModel()       { return model;       }
    public Double  getTemperature() { return temperature; }
    public Double  getTopP()        { return topP;        }
    public Integer getMaxTokens()   { return maxTokens;   }
    public int     getTimeoutMs()   { return timeoutMs;   }
    public int     getMaxRetries()  { return maxRetries;  }
    public boolean isMock()         { return mock;        }
    public Object  getMockData()    { return mockData;    }

    public Builder toBuilder() {
        return new Builder().baseUrl(baseUrl).apiKey(apiKey).model(model)
                .temperature(temperature).topP(topP).maxTokens(maxTokens)
                .timeoutMs(timeoutMs).maxRetries(maxRetries).mock(mock).mockData(mockData);
    }

    public static Builder builder() { return new Builder(); }

    public static final class Builder {
        private String  baseUrl;
        private String  apiKey;
        private String  model;
        private Double  temperature;
        private Double  topP;
        private Integer maxTokens;
        private int     timeoutMs  = 0;
        private int     maxRetries = 0;
        private boolean mock       = false;
        private Object  mockData;

        private Builder() {}

        public Builder baseUrl(String v)     { this.baseUrl     = v; return this; }
        public Builder apiKey(String v)      { this.apiKey      = v; return this; }
        public Builder model(String v)       { this.model       = v; return this; }
        public Builder temperature(Double v) { this.temperature = v; return this; }
        public Builder topP(Double v)        { this.topP        = v; return this; }
        public Builder maxTokens(Integer v)  { this.maxTokens   = v; return this; }
        public Builder timeoutMs(int v)      { this.timeoutMs   = v; return this; }
        public Builder maxRetries(int v)     { this.maxRetries  = v; return this; }
        public Builder mock(boolean v)       { this.mock        = v; return this; }
        public Builder mockData(Object v)    { this.mockData    = v; return this; }

        public AIFuncConfig build() { return new AIFuncConfig(this); }
    }
}
