// Generated by aifn — do not edit manually.

package aifunc;

/**
 * Thrown by the engine when execution fails.
 *
 * <p>Extends {@link RuntimeException} so callers are not required to declare
 * a {@code throws} clause, but generated wrapper methods declare it explicitly
 * for documentation purposes.
 */
public final class AIFuncException extends RuntimeException {
    public AIFuncException(String message) { super(message); }
    public AIFuncException(String message, Throwable cause) { super(message, cause); }
}
