// Generated by aifn — do not edit manually.

using System;

namespace Aifunc;

/// <summary>
/// Thrown by the engine when execution fails.
/// </summary>
public sealed class AIFuncException : Exception
{
    public AIFuncException(string message) : base(message) {}
    public AIFuncException(string message, Exception? inner) : base(message, inner) {}
}
