// Generated by aifn — do not edit manually.

namespace Aifunc;

/// <summary>
/// Controls the function's runtime mode and model connection.
/// Use object initializers to construct an instance.
/// </summary>
public sealed class AIFuncConfig
{
    public string? BaseUrl { get; init; }
    public string? ApiKey { get; init; }
    public string? Model { get; init; }
    public double? Temperature { get; init; }
    public double? TopP { get; init; }
    public int? MaxTokens { get; init; }
    public int TimeoutMs { get; init; } = 0;
    public int MaxRetries { get; init; } = 0;
    public bool Mock { get; init; } = false;
    public object? MockData { get; init; }

    /// <summary>
    /// Returns a copy with selected properties overridden (mirrors Java <c>toBuilder</c>).
    /// Pass <paramref name="mockData"/> together with <paramref name="setMockData"/>=<c>true</c>
    /// to replace or clear mock data (including setting it to <c>null</c>).
    /// </summary>
    public AIFuncConfig With(
        string? baseUrl = null,
        string? apiKey = null,
        string? model = null,
        double? temperature = null,
        double? topP = null,
        int? maxTokens = null,
        int? timeoutMs = null,
        int? maxRetries = null,
        bool? mock = null,
        object? mockData = null,
        bool setMockData = false)
    {
        return new AIFuncConfig
        {
            BaseUrl     = baseUrl     ?? BaseUrl,
            ApiKey      = apiKey      ?? ApiKey,
            Model       = model       ?? Model,
            Temperature = temperature ?? Temperature,
            TopP        = topP        ?? TopP,
            MaxTokens   = maxTokens   ?? MaxTokens,
            TimeoutMs   = timeoutMs   ?? TimeoutMs,
            MaxRetries  = maxRetries  ?? MaxRetries,
            Mock        = mock        ?? Mock,
            MockData    = setMockData ? mockData : (mockData ?? MockData),
        };
    }

    /// <summary>Returns a copy with <see cref="MockData"/> replaced.</summary>
    public AIFuncConfig WithMockData(object? mockData) =>
        With(mockData: mockData, setMockData: true);
}
